from __future__ import annotations


class EffectType:
    NOOP = "NOOP"
    EMIT_ARTIFACT = "EMIT_ARTIFACT"
    ASSERT_CONTRACT = "ASSERT_CONTRACT"
    VERIFY_EPOCH = "VERIFY_EPOCH"
    VERIFY_SIGNATURE = "VERIFY_SIGNATURE"
    SELECT_MEASUREMENT_TRACK = "SELECT_MEASUREMENT_TRACK"
    LOWER_BACKEND_IR = "LOWER_BACKEND_IR"
    LOWER_QASM = "LOWER_QASM"
    BUNDLE_EVIDENCE = "BUNDLE_EVIDENCE"
    INVERT_CONSTRAINTS = "INVERT_CONSTRAINTS"
