from __future__ import annotations


class EffectType:
    NOOP = "NOOP"
    EMIT_ARTIFACT = "EMIT_ARTIFACT"
    ASSERT_CONTRACT = "ASSERT_CONTRACT"
    VERIFY_EPOCH = "VERIFY_EPOCH"
    VERIFY_SIGNATURE = "VERIFY_SIGNATURE"
    SELECT_MEASUREMENT_TRACK = "SELECT_MEASUREMENT_TRACK"
    CHECK_REPO_STATE = "CHECK_REPO_STATE"
    VALIDATE_REGISTRIES = "VALIDATE_REGISTRIES"
    VALIDATE_COUPLING_TOPOLOGY = "VALIDATE_COUPLING_TOPOLOGY"
    VALIDATE_QUANTUM_SEMANTICS = "VALIDATE_QUANTUM_SEMANTICS"
    SIGN_BUNDLE = "SIGN_BUNDLE"
    VERIFY_BUNDLE = "VERIFY_BUNDLE"
    LOWER_BACKEND_IR = "LOWER_BACKEND_IR"
    LOWER_QASM = "LOWER_QASM"
    BUNDLE_EVIDENCE = "BUNDLE_EVIDENCE"
    INVERT_CONSTRAINTS = "INVERT_CONSTRAINTS"
